apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_PREFIX-service
spec:
  selector:
    matchLabels:
      app: APP_PREFIX-service
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: APP_PREFIX-service
    spec:
      containers:
        - name: APP_PREFIX-service
          image: DOCKER_SERVER/bnasslahsen/devops-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
      imagePullSecrets:
        - name: APP_PREFIX-registry
---
apiVersion: v1
kind: Service
metadata:
  name: APP_PREFIX-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: APP_PREFIX-service